### ISSUE TITLE
'Serial3' was not declared in this scope

### ISSUE THREAD

**Issue by niyazialpay** [oguzhanbaser/ethernet#1]
'Serial3' was not declared in this scope

Böyle bir hata alıyorum compile işleminde. Aynı Serial3 komutu daha önceki satırlarda da olmasına rağmen yalnızca 126. satırda veriyor. Arduino UNO kullanıyorum, problem ne olabilir?

**Comment by niyazialpay** [comment]
Serial3 olan satırları Serial olarak replace ettim bu sefer de upload işleminde aşağıdaki gibi hata alıyorum

avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x30

**Comment by oguzhanbaser** [comment]
Merhaba Muhammed bey..

Arduino normalde seri port üzerinden programlanan bir denetleyicidir. Bu
yüzden de programlamaya çalışırken eş zamanlı olarak başka bir cihaz ile
haberleşemez ve söylemiş olduğunuz hatayı verir.

Eğer herhangi bir haberleşme modülü Arduino nun 0 ve 1 (rx - tx) pinlerine
bağlı değilse ve hala aynı hatayı programlamaya çalışırken veriyorsa bir
çok sebepten kaynaklanan bir hata olabilir ama en çok karşılaştığım Arduino
nun haberleşme çipi nin zarar hasar almasıyla meydana gelendir ki çözümü
ftdi çipini değişmek yada yeni Arduino almaktadır..

Umarım yardımcı olabilmişimdir. İyi çalışmalar..
5 Mar 2016 23:53 tarihinde "Muhammed Niyazi Alpay" notifications@github.com
yazdı:

**Comment by niyazialpay** [comment]
Teşekkür ederim, 0 ve 1 pinindeki bağlantıyı kestiğimde upload işlemini yaptı. Serial3 olan komutları Serial olarak değiştirerek yükledim ancak wifi bağlantısı olmuyor. Modem arayüzünden client listesine baktığımda bağlı cihaz göremiyorum, nerde hata yapıyor olabilirim. Serial3 ile ilgili bir problem var sanırım ama anlayamadım. Arduino programlamaya da yeni başladığım için çok bilgim de bulunmuyor açıkçası.

**Comment by oguzhanbaser** [comment]
Merhabalar..

Esp8266 yi Arduino uno yada nano gibi tek serial donanımina sahip cihazlar
ile kullanmak son derece zor. Ben denedim ancak başarılı olduğum
söylenemez. Ancak ilk fırsatta tekrar bakacağım bir gelişme kaydedersem
sitede paylaşım yaparım.

Beklemek istemezseniz farklı sitelerden uno için yardım alabilirsiniz yada
bir mega temin ederek benim paylaştığım yazılımı kullanabilirsiniz.

İyi çalışmalar..
6 Mar 2016 13:06 tarihinde "Muhammed Niyazi Alpay" notifications@github.com
yazdı:

**Comment by niyazialpay** [comment]
Bilgi için teşekkür ederim
